name: Booking Genius Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
          # i need cd project folder and install composer

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest
        working-directory: project

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: project

      - name: Set up environment variables in .env existing file
        run: |
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=cleantech_affiliate_new/g' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=cleantech_affiliate_new/g' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=affiliate_new/g' .env
        working-directory: project

      - name: Generate Application Key
        run: php artisan key:generate
        working-directory: project

      - name: Download ftp-deploy script
        run: |
          curl -sSL https://raw.githubusercontent.com/lukasmartinelli/ftp-deploy/master/ftp-deploy -o ftp-deploy
          chmod +x ftp-deploy

      - name: Deploy to FTP
        run: |
          ./ftp-deploy -u affiliatePro@cleantech.geniusocean.net -p affiliatePro -r ftp://cleantech@cleantech.geniusocean.net:7822/home/cleantech/public_html/affiliate-new
